function out = StorageInventory( obj, startdt, facility, valuetype )
%STORAGEINVENTORY download stoage inventory.  This will download the
%inventory MTM schedule generated by the Pastore model by default.  Setting
%Valuetype to prompt will download the inventory and value at the pormpt.

%parse input and set default
if nargin < 1;    
    startdt = datestr(datenum(date())-1, char(gist.environment.nargsin('Programs', mfilename, obj.databaseSource)));  
end
if nargin < 2; facility = 'Inventory';                                           end
if nargin < 3; valuetype = [];                                          end

if isnumeric(startdt)
    startdt = datestr(startdt, char(gist.environment.nargsin('Programs', mfilename, obj.databaseSource)));
end

% download fields 


if iscell(facility) || ischar(facility)
   % make a single quote delikmited list
   
   idx = strfind(facility, '''');
   if iscell(facility)
       idx = cellfun(@isempty, idx);
   end
   if all(idx)
       %only add single quote if none found
       facility = strcat('''',facility,'''');
   else
       error('Single quotes not allowed in facility name');
   end
end

if ~isempty(valuetype)
    error('This valuetype for storage inventory is not available at this tiem');
    %Does not work must modify storage modelling so inventory has fieldname
    out = strcat(' Select * from storage_inputs ', ...
        ' where MarkDate = ''', startdt, ''' ', ...
        ' AND FieldName = ''', facility, ''' ', ...
        ' AND InputName = ''Physical Inventory'' ');
else
    out = strcat( ...
          ' SELECT * ', ...
          '   WHERE FacilityName in (', facility, ') ', ...
          '   AND FieldName in (''Intrinsic Exposure'', ''Liquidation Schedule'') ', ...
          '   AND MarkDate = ''', startdt, '''  ');
  
end
