function out = StorageExposures( obj, startdt, enddt, facility, valuetype )
%STORAGEEXPOSURES download stoage inventory.  This will download the
%inventory MTM schedule generated by the Pastore model by default.  Setting
%Valuetype to prompt will download the inventory and value at the pormpt.

%parse input and set default
if nargin < 1;    
    startdt = datestr(datenum(date())-1, char(gist.environment.nargsin('Programs', mfilename, obj.databaseSource)));  
end
if nargin < 3; facility = 'Inventory';                                           end
if nargin < 43; valuetype = [];                                          end

if isnumeric(startdt)
    startdt = datestr(startdt, char(gist.environment.nargsin('Programs', mfilename, obj.databaseSource)));
end
if isnumeric(enddt)
    enddt = datestr(enddt, char(gist.environment.nargsin('Programs', mfilename, obj.databaseSource)));
end
% download fields 
flds = '''Intrinsic Exposure'', ''Liquidation Schedule''';

if ~isempty(valuetype)
    error('This valuetype for storage inventory is not available at this time');
    %Does not work must modify storage modelling so inventory has fieldname
    t1 = strcat(' Select * from storage_inputs ', ...
        ' where MarkDate = ''', startdt, ''' ', ...
        ' AND FieldName = ''', facility, ''' ', ...
        ' AND InputName = ''Physical Inventory'' ');
    flds = '''Intrinsic Exposure''';

end
out = strcat( ...
      ' SELECT * FROM storage_results ', ...
      '   WHERE FacilityName in (', facility, ') ', ...
      '   AND FieldName in (', flds, ') ', ...
      '   AND MarkDate between ''', startdt, ''' and ''', enddt, ''' ', ...
      '   ORDER by FacilityName, FieldName, MarkDate, ContractMonth');
  
